
using HarmonyLib;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Factories;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Runs;

///This patch will prevent multiple curses being generated by Rotten Diaphragm
[HarmonyPatch(typeof(CardFactory), nameof(CardFactory.CreateForReward), new Type[] { typeof(Player), typeof(IEnumerable<CardModel>), typeof(CardCreationOptions) })]
public static class CardRewardWithCursesPatch
{
    public static bool GeneratedCurseThisCardReward {get; set;}
    public static void ResetFlag()
    {
        GeneratedCurseThisCardReward = false;
    }

    private static void MarkCurseGenerated(CardModel __result)
    {
        if (__result.Type == MegaCrit.Sts2.Core.Entities.Cards.CardType.Curse)
        {
            GeneratedCurseThisCardReward = true;
        }
    }

    public static void Postfix(CardModel __result)
    {
        // Check if the card generated by the original method was a curse
        MarkCurseGenerated(__result);
    }
}
